### PR TITLE
RDS DBInstance resource

### PR DESCRIPTION
**Pull request by ktheory**
:wave: Here's a simple little resource for RDS instances.

It's not complete, but it's a start.

It adds:

- `Aws::RDS::Resource#create_db_instance` (returns a DBInstance)
- `Aws::RDS::Resource#db_instances` (returns a collection of DBInstances)
- `Aws::RDS::DBInstance#modify`
- `Aws::RDS::DBInstance#delete`

Here's an example walkthrough with required arguments:
```
Aws::RDS::Resource.new.db_instances # Collection of DB instances

# Create a new DB instance
db  = Aws::RDS::Resource.new.create_db_instance(
  db_instance_identifier: 'example-db',
  allocated_storage: 5,
  db_instance_class: 'db.t1.micro',
  engine: 'mysql',
  master_username: 'foo',
  master_user_password: '12345678'
)

# Wait until db_instance_status is available, then modify it:
db.modify(allocated_storage: 6, apply_immediately: true)

# Shut it down
db.delete(skip_final_snapshot: true)
```

No errors from `rake resources:validate` (except an unrelated S3 issue)

### CODE REVIEW

**Comment by trevorrowe** [comment]
Sorry for the slow response. I've been out-of-the office and I am just getting back into things. I'll try to take a look at this and see about getting this merged. I'm working on a minor refactoring of the resource definition structure, but it wouldn't require many changes to make this work (very trivial ones).

**Comment by ktheory** [comment]
Thanks, Trevor.

(Honestly no need to apologize. That's how it goes with OSS.)

**Comment by trevorrowe** [comment]
I've finalized the refactor of the resource definitions. There are some minor changes required for this to work again. The primary differences are:

* All top-level resources should now have a "has" association in the "service" section of the model. This is what the SDK will use to provide methods such as `rds.db_instance(id)`. The structure of a "has" association is the same as a "hasMany".

  ```ruby
  {
    "service": {
      "has": {
        "DBInstance": {
          "resource": {
            "type": "DBInstance",
            "identifiers": [ ... ]
          }
        }
      }
    }
  }
  ```

* All resource identifier lists and request parameter lists that provide a **target/sourceType/source** need updating. The "sourceType" attribute is now just "source", and the the previous "source" is now contextual to the source. For example:

  ```ruby
  # old
  { "target": "DBInstanceIdentifier", "sourceType": "identifier", "source": "Id" }
  # new
  { "target": "DBInstanceIdentifier", "source": "identifier", "identifierName": "Id" }

  # old
  { "target": "Id", "sourceType": "responsePath", "source": "DBInstances[].DBInstanceIdentifier" }
  # new
  { "target": "Id", "source": "responsePath", "path": "DBInstances[].DBInstanceIdentifier" }
  ```

**Comment by ktheory** [comment]
@trevorrowe: Updated per your comment. The walkthrough in the PR description works the same, as does `Aws::RDS::Resource.new.db_instance(my_db_id)`.

Oh, and I figured out that `identifierName` should just be `name` in your comment. :wink:.

**Comment by ktheory** [comment]
Oh, and as an aside/pro-tip, I spent more time than I'd like trying to track down a JSON syntax error (missing colon).

Parsing the file as YAML gives more accurate line numbers for the error than JSON. E.g.
```
ruby -ryaml -e 'YAML.load_file("aws-sdk-core/apis/RDS.resources.json")'
```

**Comment by trevorrowe** [comment]
This has been merged into master of aws/aws-sdk-ruby: https://github.com/aws/aws-sdk-ruby/commit/496c5fc6582d6113cdb8334906985b0ba628bbcc

Sorry for taking a while. I reached out to the RDS team to get input on the interface. I'm going to continue to expand on this interface based on their input. Hopefully we can cover the full RDS interface.

Thanks again!

**Comment by ktheory** [comment]
Yay, thanks.

**Pull request closed without merging**
